/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vMc4rgHqm8o
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function LoginForm() {
  return (
    (<Card className="mx-auto max-w-md">
      <CardHeader className="space-y-2">
        <CardTitle className="text-3xl font-bold">Login</CardTitle>
        <CardDescription>Welcome back to Cheers!</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="username">mail address</Label>
          <Input id="username" placeholder="Enter your mail address" required type="text" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" required type="password" />
        </div>
        <Button className="w-full" type="submit">
          Login
        </Button>
      </CardContent>
    </Card>)
  );
}